---
name: Backup-SingleFile
version: 0.08
author:
  - 'Ingo LANTSCHNER <perl@lantschner.name>'
abstract: copies one file to a predefined backup-directory, appends the date and a counter for keeping the history.
license: perl
configure_requires:
  File::Glob: 0
  File::Spec::Functions: 0
  FindBin: 1.49
  SUPER: 0
requires:
  Carp: 0
  File::Basename: 0
  File::Copy: 2.13
  Time::localtime: 1.02
  base: 2.13
  perl: 5.8.0
build_requires:
  File::Glob: 0
  File::Path: 0
  File::Spec::Functions: 0
  FindBin: 1.49
  SUPER: 0
  Test::Cmd: 1.05
  Test::File: 1.29
  Test::More: 0.62
  Test::NoWarnings: 0.084
  Test::Output: 0.16
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Backup::SingleFile:
    file: lib/Backup/SingleFile.pm
    version: 0.08
resources:
  license: http://dev.perl.org/licenses/
