---
name: Backup-SingleFile
version: 0.12
author:
  - 'Ingo LANTSCHNER <perl@lantschner.name>'
abstract: 'copies one file to a predefined backup-directory, appends the date and a counter for keeping the history.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  File::Glob: 0
  File::Spec::Functions: 0
  FindBin: 0
  SUPER: 0
requires:
  Carp: 0
  Exporter: 0
  File::Basename: 0
  File::Copy: 0
  Time::localtime: 0
  base: 0
  perl: 5.8.0
build_requires:
  File::Glob: 0
  File::Path: 0
  File::Spec::Functions: 0
  FindBin: 0
  SUPER: 0
  Sub::Identify: 0
  Test::Cmd: 0
  Test::File: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
provides:
  Backup::SingleFile:
    file: lib/Backup/SingleFile.pm
    version: 0.12
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
