---
name: Backup-SingleFile
version: 0.01
author:
  - 'Ingo LANTSCHNER <ingo@boxbe.com>'
abstract: "erstellt Backups einzelner Dateien (inkl. History)"
license: perl
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Backup::SingleFile:
    file: lib/Backup/SingleFile.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
