---
name: Backup-SingleFile
version: 0.05
author:
  - 'Ingo LANTSCHNER <perl@lantschner.name>'
abstract: copies one file to a predefined backup-directory, appends the date and a counter for keeping the history.
license: perl
configure_requires:
  SUPER: 0
requires:
  Carp: 0
  File::Basename: 0
  File::Copy: 0
  Time::localtime: 0
  perl: 5.10.0
build_requires:
  File::Glob: 0
  File::Path: 0
  File::Spec::Functions: 0
  FindBin: 0
  Test::Cmd: 0
  Test::File: 0
  Test::More: 0
  Test::Output: 0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Backup::SingleFile:
    file: lib/Backup/SingleFile.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
